<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Usuario;
use App\Models\Ejidatario;
use Illuminate\Support\Facades\Hash;

class EjidatarioSeeder extends Seeder
{
    public function run()
    {
        $datosDart = [
            ['CARMEN', 'AGUILAR', 'AGUIRRE'],
            ['MARIA ISABEL C.', 'AGUILAR', 'CAMPOS'],
            ['ASENCION', 'AGUILAR', 'CASTILLO'],
            ['LUIS', 'AGUILAR', 'ESPINOZA'],
            ['MAXIMINO', 'AGUILAR', 'ESPINOZA'],
            ['BENITO', 'AGUILAR', 'FLORES'],
            ['CLAUDIO', 'AGUILAR', 'HERNANDEZ'],
            ['GILBERTO', 'AGUILAR', 'HERNANDEZ'],
            ['DONATO', 'AGUILAR', 'MEZA'],
            ['AGUSTIN', 'AGUILAR', 'MIRANDA'],
            ['CRUZ', 'AGUILAR', 'MIRANDA'],
            ['ODILON', 'AGUILAR', 'MIRANDA'],
            ['RUPERTO', 'AGUIRRE', 'PEREZ'],
            ['GENOVEVA MARCELA', 'AGUIRRE', 'SUAREZ'],
            ['HILARIO', 'ARIAS', 'MIRANDA'],
            ['FELIX', 'BARRON', 'AGUIRRE'],
            ['VICTOR', 'BARRON', 'AGUIRRE'],
            ['JOEL', 'BARRON', 'DAVALOS'],
            ['BONFILIO', 'BARRON', 'OLMOS'],
            ['HUMBERTO', 'BARRON', 'OLMOS'],
            ['ISMAEL', 'BARRON', 'OLMOS'],
            ['JAVIER', 'BARRON', 'OLMOS'],
            ['MARGARITA', 'BERNARDINO', 'VAZQUEZ'],
            ['MATILDE', 'BERNARDINO', 'VAZQUEZ'],
            ['RAFAEL', 'BERNARDINO', 'VAZQUEZ'],
            ['MANUELA', 'BOBADILLA', 'CABALLERO'],
            ['ALEJANDRA', 'BRINDIS', 'ESPINOZA'],
            ['HERMINIO', 'BRINDIS', 'HERNANDEZ'],
            ['CRESENCIO', 'BRINDIZ', 'AGUIRRE'],
            ['JAVIER', 'BRINDIZ', 'AGUIRRE'],
            ['JUANA', 'BRINDIZ', 'DE LA LUZ'],
            ['VICTOR', 'BRINDIZ', 'ESPINOZA'],
            ['DANIEL', 'BRINDIZ', 'FLORES'],
            ['FLORA', 'BRINDIZ', 'FLORES'],
            ['PANFILO', 'BRINDIZ', 'FLORES'],
            ['FELIMON MARTIN', 'BRINDIZ', 'OSORIO'],
            ['FERNANDO', 'BRINDIZ', 'OSORIO'],
            ['LEONOR', 'CABALLERO', 'BERNARDINO'],
            ['PEDRO', 'CABALLERO', 'BERNARDINO'],
            ['RUTH', 'CABALLERO', 'CAMPOS'],
            ['BRAULIO', 'CABALLERO', 'ESPINOZA'],
            ['CESAR', 'CABALLERO', 'ESPINOZA'],
            ['FERNANDO', 'CABALLERO', 'ESPINOZA'],
            ['ISMAEL', 'CABALLERO', 'ESPINOZA'],
            ['JUAN', 'CABALLERO', 'ESPINOZA'],
            ['MARICELA', 'CABALLERO', 'ESPINOZA'],
            ['REYNALDO', 'CABALLERO', 'ESPINOZA'],
            ['VICTOR', 'CABALLERO', 'ESPINOZA'],
            ['JOSE BENJAMIN', 'CABALLERO', 'HERNANDEZ'],
            ['RICARDO', 'CABALLERO', 'HERNANDEZ'],
            ['SALOMON TOMAS', 'CABALLERO', 'HERNANDEZ'],
            ['SARA', 'CABALLERO', 'HERNANDEZ'],
            ['JOSE', 'CABALLERO', 'MELCHOR'],
            ['BONFILIO', 'CABALLERO', 'MIRANDA'],
            ['FERMINA', 'CABALLERO', 'MIRANDA'],
            ['GABRIEL', 'CABALLERO', 'MIRANDA'],
            ['CONCEPCION', 'CABALLERO', 'OSORIO'],
            ['JUAN', 'CABALLERO', 'OSORIO'],
            ['SEBASTIAN', 'CABALLERO', 'OSORIO'],
            ['FILEMON', 'CABALLERO', 'PASTRAN'],
            ['GABRIEL', 'CABALLERO', 'PASTRAN'],
            ['NICANOR', 'CABALLERO', 'PASTRAN'],
            ['ALEJANDRA JULIA', 'CABALLERO', 'PEREZ'],
            ['CARMEN', 'CABALLERO', 'PEREZ'],
            ['INOCENCIO', 'CABALLERO', 'PEREZ'],
            ['JORGE PEDRO', 'CABALLERO', 'PEREZ'],
            ['MELITON', 'CABALLERO', 'PEREZ'],
            ['NICOLAS', 'CABALLERO', 'PEREZ'],
            ['SALVADOR', 'CABALLERO', 'PEREZ'],
            ['SERGIO 1 HERM JULIA', 'CABALLERO', 'PEREZ'],
            ['SERGIO 2', 'CABALLERO', 'PEREZ'],
            ['JUAN', 'CABALLERO', 'RIOS'],
            ['ANA MARIA', 'CABALLERO', 'ROSAS'],
            ['FIDEL', 'CABALLERO', 'ROSAS'],
            ['TEODORO', 'CABALLERO', 'ROSAS'],
            ['ANGELA ZENAIDA', 'CABALLERO', 'SANCHEZ'],
            ['CECILIO DEMETRIO', 'CABALLERO', 'SANCHEZ'],
            ['TRINIDAD', 'CABALLERO', 'VAZQUEZ'],
            ['OLGA', 'CABRERA', 'CARRILLO'],
            ['SANTIAGO', 'CABRERA', 'ESPINOZA'],
            ['JOSE LUIS', 'CABRERA', 'HERNANDEZ'],
            ['CONCEPCION', 'CAMPOS', 'FLORES'],
            ['MARIA', 'CHAVARRIAS', 'AGUILAR'],
            ['ROBERTO', 'CONTRERAS', 'OLMOS'],
            ['CRESENCIO', 'DAVALOS', 'AREVALO'],
            ['ISIDRO', 'DAVALOS', 'AREVALO'],
            ['ALFREDO', 'DAVALOS', 'CORDOVA'],
            ['DOMITILO', 'DAVALOS', 'CORDOVA'],
            ['PASCUAL', 'DAVALOS', 'CORDOVA'],
            ['FRANCISCO', 'DAVALOS', 'DEL PILAR'],
            ['MANUEL', 'DAVALOS', 'DEL PILAR'],
            ['MISAEL', 'DAVALOS', 'DEL PILAR'],
            ['CASTO', 'DAVALOS', 'ESPINOZA'],
            ['FILEMON', 'DAVALOS', 'ESPINOZA'],
            ['JOSE JORGE', 'DAVALOS', 'ESPINOZA'],
            ['SERGIO', 'DAVALOS', 'ESPINOZA'],
            ['TOMAS', 'DAVALOS', 'ESPINOZA'],
            ['AMADO', 'DAVALOS', 'HERNANDEZ'],
            ['J. PEDRO ABEL', 'DAVALOS', 'HERNANDEZ'],
            ['JAIME', 'DAVALOS', 'MIRANDA'],
            ['JOSE', 'DAVALOS', 'MIRANDA'],
            ['PEDRO', 'DAVALOS', 'MIRANDA'],
            ['MANUEL', 'DAVALOS', 'PEREZ'],
            ['INOCENCIO', 'DE LA LUZ', 'CABALLERO'],
            ['JUAN', 'DE LA LUZ', 'CABALLERO'],
            ['MARIA ZARAPIA', 'OROPEZA', 'DE LA LUZ'],
            ['CARMEN', 'DE LA LUZ', 'TORIZ'],
            ['BALVINA', 'DE LA TRINIDAD', 'OSORIO'],
            ['ADELFO', 'DIAZ', 'AGUILAR'],
            ['AMADOR', 'DIAZ', 'AGUILAR'],
            ['JUAN', 'DIAZ', 'AGUILAR'],
            ['PERFECTO', 'DIAZ', 'AGUILAR'],
            ['ROSENDO', 'DIAZ', 'AGUILAR'],
            ['BRUNO', 'DIAZ', 'FLORES'],
            ['DEMETRIO', 'DIAZ', 'FLORES'],
            ['MARTHA', 'DIAZ', 'ROSAS'],
            ['MANUELA', 'DIAZ', 'MEZA'],
            ['AGUSTIN', 'DIAZ', 'ROSAS'],
            ['ANGEL', 'DIAZ', 'ROSAS'],
            ['GUILLERMO', 'DIAZ', 'ROSAS'],
            ['DOMINGO ARENAS', 'ESCUELA', 'PRIMARIA'],
            ['MARIA SANTIAGA', 'ESPINOZA', 'AGUILAR'],
            ['ROSENDO', 'ESPINOZA', 'AGUIRRE'],
            ['RAYMUNDO', 'ESPINOZA', 'ARMENTA'],
            ['FERNANDO', 'ESPINOZA', 'CABALLERO'],
            ['GERARDO', 'ESPINOZA', 'CABALLERO'],
            ['ARISTEO ANTONIO', 'ESPINOZA', 'CHAVARRIAS'],
            ['FRANCISCO', 'ESPINOZA', 'CHAVARRIAS'],
            ['EFREN', 'ESPINOZA', 'DAVALOS'],
            ['GABRIEL', 'ESPINOZA', 'FLORES'],
            ['SEVERO', 'ESPINOZA', 'FLORES'],
            ['TRINIDAD', 'ESPINOZA', 'HERNANDEZ'],
            ['SABINO', 'ESPINOZA', 'JUAREZ'],
            ['MARIA PAULA PETRA', 'ESPINOZA', 'JURADO'],
            ['MARGARITO', 'ESPINOZA', 'LOPEZ'],
            ['ELIGIO', 'ESPINOZA', 'MARIN'],
            ['FRANCISCO', 'ESPINOZA', 'MORALES'],
            ['GAVINO', 'ESPINOZA', 'MORALES'],
            ['JESUS', 'ESPINOZA', 'MORALES'],
            ['MICAELA', 'ESPINOZA', 'MORALES'],
            ['HONORIA', 'ESPINOZA', 'MUÑOZ'],
            ['GUILLERMO', 'ESPINOZA', 'OROPEZA'],
            ['PASCUAL', 'ESPINOZA', 'OROPEZA'],
            ['ARGIMINA', 'ESPINOZA', 'OSORIO'],
            ['BENJAMIN', 'ESPINOZA', 'OSORIO'],
            ['ISMAEL', 'ESPINOZA', 'OSORIO'],
            ['MARGARITA', 'ESPINOZA', 'OSORIO'],
            ['PASCUALA', 'ESPINOZA', 'OSORIO'],
            ['PABLO', 'ESPINOZA', ''],
            ['TRINIDAD', 'ESPINOZA', 'PALMA'],
            ['ANASTACIO', 'ESPINOZA', 'PEREZ'],
            ['CIRILO', 'ESPINOZA', 'PEREZ'],
            ['HILARIO', 'ESPINOZA', 'PEREZ'],
            ['JOSE INDALECIO', 'ESPINOZA', 'PEREZ'],
            ['RAMON', 'ESPINOZA', 'PEREZ'],
            ['ROBERTO', 'ESPINOZA', 'PEREZ'],
            ['TEOFILO', 'ESPINOZA', 'PEREZ'],
            ['ERASMO', 'ESPINOZA', 'RAMIREZ'],
            ['JUAN', 'ESPINOZA', 'RAMIREZ'],
            ['MACLOVIA', 'ESPINOZA', 'RAMIREZ'],
            ['MAXIMINO', 'ESPINOZA', 'RAMIREZ'],
            ['RAFAEL', 'ESPINOZA', 'RAMIREZ'],
            ['JUVENCIA', 'ESPINOZA', 'SANDOVAL'],
            ['GUSTAVO', 'ESPINOZA', 'IGLESIAS'],
            ['MARIA GUADALUPE', 'ESPINOZA', 'SANCHEZ'],
            ['JUANA', 'ESPINOSA', 'VALLEJO'],
            ['RICARDO', 'ESPINOZA', 'VALLEJO'],
            ['ROBERTO', 'ESPINOZA', 'VALLEJO'],
            ['FILIBERTA', 'ESPINOZA', 'VARGAS'],
            ['FLORENCIO', 'ESPINOZA', 'VARGAS'],
            ['GERARDO', 'ESPINOZA', 'VARGAS'],
            ['GIL', 'ESPINOZA', 'VARGAS'],
            ['MARGARITA', 'ESPINOZA', 'VARGAS'],
            ['PASCUALA', 'ESPINOZA', 'VARGAS'],
            ['TEODORO', 'ESPINOZA', 'VARGAS'],
            ['GABRIEL', 'ESPINOZA', 'VAZQUEZ'],
            ['EVA', 'FLORES', 'HUESCA'],
            ['NAZARIO', 'FLORES', 'LOPEZ'],
            ['IGNACIO', 'FLORES', 'MARIN'],
            ['ANSELMO', 'FLORES', 'SANCHEZ'],
            ['PASCUAL', 'HERMENEGILDO', 'CHAVARRIAS'],
            ['HERIBERTO', 'HERNANDEZ', 'DEL PILAR'],
            ['PEDRO', 'HERNANDEZ', 'DEL PILAR'],
            ['MARGARITO', 'HERNANDEZ', 'DIAZ'],
            ['SALVADOR', 'HERNANDEZ', 'DIAZ'],
            ['RAFAELA', 'HERNANDEZ', 'ESPINOZA'],
            ['FILOMENA', 'HERNANDEZ', 'OSORIO'],
            ['PASCUAL', 'HERNANDEZ', 'OSORIO'],
            ['CANDIDO', 'HERNANDEZ', 'PEREZ'],
            ['JOSE CRUZ', 'HERNANDEZ', 'PEREZ'],
            ['JUSTO', 'HERNANDEZ', 'PEREZ'],
            ['ROBERTA', 'HERNANDEZ', 'ROJAS'],
            ['TOMAS', 'HERNANDEZ', 'FLORES'],
            ['JOAQUINA', 'HERNANDEZ', 'SANDOVAL'],
            ['DANIEL', 'HERNANDEZ', 'TRINIDAD'],
            ['FIDENCIO', 'IGLESIAS', 'AGUIRRE'],
            ['MARTINA', 'IGLESIAS', 'AGUIRRE'],
            ['MEDARDO', 'IGLESIAS', 'AGUIRRE'],
            ['CATALINA', 'IGLESIAS', 'CABALLERO'],
            ['MARCELINO', 'IGLESIAS', 'CABALLERO'],
            ['PETRA', 'JIMENEZ', 'LOPEZ'],
            ['MAXIMO', 'JUAREZ', 'AGUILAR'],
            ['MARIA REMEDIOS', 'JUAREZ', 'AGUIRRE'],
            ['ANASTACIO', 'JUAREZ', 'CESAREO'],
            ['ELIA', 'JUAREZ', 'DE LA LUZ'],
            ['SAUL', 'JUAREZ', 'DE LA LUZ'],
            ['ALEJANDRINO', 'JUAREZ', 'ESPINOZA'],
            ['CAMILO', 'JUAREZ', 'ESPINOZA'],
            ['FAUSTINO', 'JUAREZ', 'ESPINOZA'],
            ['FRANCISCO', 'JUAREZ', 'ESPINOZA'],
            ['JOSE PERFECTO', 'JUAREZ', 'ESPINOZA'],
            ['JUAN', 'JUAREZ', 'ESPINOZA'],
            ['ADALBERTO', 'JUAREZ', 'HERNANDEZ'],
            ['FRANCISCA', 'LIRA', 'SEGUNDO'],
            ['RUFINA', 'LIRA', 'SEGUNDO'],
            ['LUIS', 'LOZANO', 'DE LA TRINIDAD'],
            ['MARCOS', 'LOZANO', 'OLVERA'],
            ['FELIPE', 'LOZANO', 'OSORIO'],
            ['GENARO', 'LOZANO', 'OSORIO'],
            ['IRINEO', 'LOZANO', 'OSORIO'],
            ['ANGELICA', 'MARTINEZ', 'MIGUEL'],
            ['JOSE PEDRO JUVENAL', 'MARTINEZ', 'OROPEZA'],
            ['MARIA', 'MIRANDA', 'JUAREZ'],
            ['ANASTACIO', 'MORALES', 'OLMOS'],
            ['LORENZO', 'MORALES', 'OLMOS'],
            ['MARCELINO', 'MORALES', 'OLMOS'],
            ['FRANCISCO', 'MORENO', 'JUAREZ'],
            ['JOSE ASENCION', 'MUÑOZ', 'CESAREO'],
            ['JOSE TEODORO', 'MUÑOZ', 'CESAREO'],
            ['MARCELO', 'OJEDA', 'DAVALOS'],
            ['OBDULIO', 'OJEDA', 'DAVALOS'],
            ['ELIAS', 'OJEDA', 'ESPINOZA'],
            ['JOSE JUVENTINO', 'OJEDA', 'RODRIGUEZ'],
            ['MANUEL', 'OJEDA', 'RODRIGUEZ'],
            ['PLUTARCO', 'OJEDA', 'RODRIGUEZ'],
            ['ODILON', 'OJEDA', 'VAZQUEZ'],
            ['GREGORIO', 'OLMOS', 'ESPINOZA'],
            ['ASUNCION', 'OLMOS', 'HERNANDEZ'],
            ['CIRILO', 'OLMOS', 'HERNANDEZ'],
            ['MARCELO', 'OLMOS', 'HERNANDEZ'],
            ['ENRIQUE', 'OLMOS', 'SEGUNDO'],
            ['AURORA', 'OLVERA', 'MOCTEZUMA'],
            ['LUCIO', 'OROPEZA', 'ESPINOZA'],
            ['LUCAS', 'OROPEZA', 'ESPINOZA'],
            ['ANASTACIO', 'OROPEZA', 'OSORIO'],
            ['CARMEN', 'OROPEZA', 'OSORIO'],
            ['GERARDO', 'OROPEZA', 'OSORIO'],
            ['JUAN ASCENCION', 'OROPEZA', 'OSORIO'],
            ['MARGARITO', 'OROPEZA', 'OSORIO'],
            ['PASCUALA', 'OROPEZA', 'OSORIO'],
            ['MARCIANO', 'OROPEZA', 'RAMIREZ'],
            ['ELIZA', 'OROPEZA', 'SANCHEZ'],
            ['DAVID', 'OROPEZA', 'SUAREZ'],
            ['DELFINO', 'OROPEZA', 'SUAREZ'],
            ['ESTEBAN', 'OROPEZA', 'SUAREZ'],
            ['PETRA', 'OROPEZA', 'SUAREZ'],
            ['FLORENCIO', 'ORTIZ', 'JIMENEZ'],
            ['GABINO', 'OSORIO', 'AGUILAR'],
            ['ROSALINO', 'OSORIO', 'AGUILAR'],
            ['EVERARDO', 'OSORIO', 'AGUIRRE'],
            ['MARTINA', 'OSORIO', 'AGUIRRE'],
            ['FLORENCIO', 'OSORIO', 'ALMAZAN'],
            ['JOSE VICTOR DAVID', 'OSORIO', 'BERNARDINO'],
            ['LEOPOLDO', 'OSORIO', 'BERNARDINO'],
            ['JAIME', 'OSORIO', 'CABALLERO'],
            ['HILARIA', 'OSORIO', 'CABRERA'],
            ['GUILLERMO', 'OSORIO', 'CAMPOS'],
            ['FELIPE', 'OSORIO', 'CASTILLO'],
            ['CAMILO', 'OSORIO', 'DAVALOS'],
            ['CELSO', 'OSORIO', 'DAVALOS'],
            ['FELIPE', 'OSORIO', 'DAVALOS'],
            ['FRANCISCO', 'OSORIO', 'ESPINOZA'],
            ['MISRRAIM', 'OSORIO', 'ESPINOZA'],
            ['ALFREDO', 'OSORIO', 'HERNANDEZ'],
            ['APOLINAR JAIME', 'OSORIO', 'HERNANDEZ'],
            ['GREGORIO', 'OSORIO', 'HERNANDEZ'],
            ['JAVIER', 'OSORIO', 'HERNANDEZ'],
            ['FELIPE', 'OSORIO', 'JUAREZ'],
            ['APOLINAR', 'OSORIO', 'LOZANO'],
            ['FRANCISCO', 'OSORIO', 'MEZA'],
            ['ROBERTO', 'OSORIO', 'MONTAÑO'],
            ['EULALIO', 'OSORIO', 'MORENO'],
            ['TEODORO', 'OSORIO', 'OJEDA'],
            ['MARIA MERCEDES', 'OSORIO', 'OROPEZA'],
            ['ARTURO', 'OSORIO', 'OSORIO'],
            ['HIGINIO', 'OSORIO', 'OSORIO'],
            ['PEDRO', 'OSORIO', 'OSORIO'],
            ['BENITO', 'OSORIO', 'PARRA'],
            ['DANIEL', 'OSORIO', 'PARRA'],
            ['FAUSTINO', 'OSORIO', 'PARRA'],
            ['FRANCISCO', 'OSORIO', 'PARRA'],
            ['ODILON', 'OSORIO', 'PARRA'],
            ['INES', 'OSORIO', 'PEREZ'],
            ['JOSEFA', 'OSORIO', 'PEREZ'],
            ['VICENTE', 'OSORIO', 'PEREZ'],
            ['JOSE NOE PANFILO', 'OSORIO', 'RIOS'],
            ['ALBERTO', 'OSORIO', 'SANCHEZ'],
            ['JUAN RODOLFO', 'OSORIO', 'SANCHEZ'],
            ['JUVENTINO', 'OSORIO', 'SANCHEZ'],
            ['ANASTACIA', 'OSORIO', 'TORIZ'],
            ['ELIAS', 'OSORIO', 'VAZQUEZ'],
            ['LAZARO', 'PADILLA', 'HERNANDEZ'],
            ['FELICITAS', 'PADILLA', 'PEREZ'],
            ['JESUS', 'PADILLA', 'PEREZ'],
            ['JUAN', 'PADILLA', 'PEREZ'],
            ['AMBROCIA GUADALUPE', 'PADRON', 'SANCHEZ'],
            ['ARCANGEL', 'PARROQUIA SAN', 'RAFAEL'],
            ['CLEOTILDE', 'PEREZ', 'AGUIRRE'],
            ['ISABEL', 'PEREZ', 'DAVALOS'],
            ['CANDELARIO', 'PEREZ', 'DIAZ'],
            ['ALFONSO', 'PEREZ', 'ESPINOZA'],
            ['FELIPE', 'PEREZ', 'ESPINOZA'],
            ['JOSE', 'PEREZ', 'ESPINOZA'],
            ['JOSE LUIS', 'PEREZ', 'ESPINOZA'],
            ['JOSE MARIA', 'PEREZ', 'ESPINOZA'],
            ['MANUEL', 'PEREZ', 'ESPINOZA'],
            ['PABLO', 'PEREZ', 'ESPINOZA'],
            ['PEDRO', 'PEREZ', 'ESPINOZA'],
            ['ZEFERINO', 'PEREZ', 'ESPINOZA'],
            ['ANDRES', 'PEREZ', 'HERNANDEZ'],
            ['ODILON', 'PEREZ', 'HERNANDEZ'],
            ['RITO', 'PEREZ', 'HERNANDEZ'],
            ['ROBERTA', 'PEREZ', 'HERNANDEZ'],
            ['MARIA DE LA LUZ', 'PEREZ', 'MAGAÑA'],
            ['JOSE ROBERTO', 'PEREZ', 'MORALES'],
            ['GAVINO', 'PEREZ', 'MORENO'],
            ['JUAN', 'PEREZ', 'MORENO'],
            ['JULIA', 'PEREZ', 'NEGRETE'],
            ['RAFAELA', 'PEREZ', 'OSORIO'],
            ['ANGEL', 'PEREZ', 'PEREZ'],
            ['FORTINO', 'PEREZ', 'SEGUNDO'],
            ['TEODORO ALFONSO', 'PEREZ', 'VAZQUEZ'],
            ['MARINA', 'RAMIREZ', 'OSORIO'],
            ['JOAQUINA', 'RIOS', 'AGUILAR'],
            ['MARTIN', 'RIOS', 'AGUILAR'],
            ['NICOLAS', 'RIOS', 'AGUILAR'],
            ['ADRIAN', 'RIOS', 'CHAVARRIAS'],
            ['EUSEBIO', 'RIOS', 'CHAVARRIAS'],
            ['CARMEN', 'RIOS', 'ESPINOZA'],
            ['MICAELA', 'RIOS', 'ESPINOZA'],
            ['AMBROCIO', 'RIOS', 'IGLESIAS'],
            ['ELENA', 'RIOS', 'IGLESIAS'],
            ['HIPOLITO', 'RIOS', 'IGLESIAS'],
            ['JOAQUIN', 'RIOS', 'IGLESIAS'],
            ['ARCADIO', 'RIOS', 'PEREZ'],
            ['FAUSTO', 'RIOS', 'PEREZ'],
            ['HERON', 'RIOS', 'PEREZ'],
            ['MAGDALENO', 'RIOS', 'PEREZ'],
            ['RAFAEL', 'RIOS', 'PEREZ'],
            ['MARCIAL', 'RIOS', 'SANCHEZ'],
            ['JOSE MAURO', 'RODRIGUEZ', 'OJEDA'],
            ['JUAN', 'RODRIGUEZ', 'OJEDA'],
            ['RITO', 'RODRIGUEZ', 'OJEDA'],
            ['AGUSTIN', 'RODRIGUEZ', 'SANCHEZ'],
            ['FLORENTINO', 'ROSAS', 'AGUIRRE'],
            ['ANTONIO', 'ROSAS', 'PEREZ'],
            ['BENJAMIN', 'SANCHEZ', 'AGUIRRE'],
            ['CLAUDIO', 'SANCHEZ', 'AGUIRRE'],
            ['JOSE', 'SANCHEZ', 'AGUIRRE'],
            ['CRISTOBAL', 'SANCHEZ', 'ESPINOZA'],
            ['DELFINO', 'SANCHEZ', 'ESPINOZA'],
            ['GERMAN', 'SANCHEZ', 'ESPINOZA'],
            ['MANUEL', 'SANCHEZ', 'FLORES'],
            ['MIGUEL', 'SANCHEZ', 'HERNANDEZ'],
            ['PEDRO', 'SANCHEZ', 'HERNANDEZ'],
            ['AGUSTIN', 'SANCHEZ', 'OROPEZA'],
            ['ENRIQUE', 'SANCHEZ', 'OSORIO'],
            ['CARLOS', 'SANCHEZ', 'PARRA'],
            ['HILARIO', 'SEGUNDO', 'ESPINOZA'],
            ['J. ASCENCION', 'SEGUNDO', 'JUAREZ'],
            ['JOSE ANTONIO', 'SEGUNDO', 'MONTAÑO'],
            ['FRANCISCO', 'SEGUNDO', 'PEREZ'],
            ['GREGORIO', 'SEGUNDO', 'PEREZ'],
            ['LUIS', 'SEGUNDO', 'PEREZ'],
            ['MARTINA', 'SEGUNDO', 'PEREZ'],
            ['ROGACIANO', 'SEGUNDO', 'PEREZ'],
            ['GRACIANO', 'SILVA', 'AGUIRRE'],
            ['JUAN', 'SILVA', 'DAVALOS'],
            ['RAFAEL', 'SILVA', 'DAVALOS'],
            ['JUAN MARTIN', 'SILVA', 'VALLES'],
            ['OCTAVIO', 'SILVA', 'VALLES'],
            ['PEDRO', 'SUAREZ', 'CORTES'],
            ['ARCADIO', 'SUAREZ', 'OSORIO'],
            ['EUSEBIO', 'SUAREZ', 'OSORIO'],
            ['FELIX 1 ', 'SUAREZ', 'OSORIO'],
            ['FELIX 2 (CALANZINGO)', 'SUAREZ', 'OSORIO'],
            ['FRANCISCO', 'SUAREZ', 'OSORIO'],
            ['NARCIZO', 'SUAREZ', 'OSORIO'],
            ['PEDRO', 'SUAREZ', 'OSORIO'],
            ['RUFINO', 'SUAREZ', 'OSORIO'],
            ['SAMUEL', 'SUAREZ', 'OSORIO'],
            ['WVILLADO', 'TORIZ', 'CHAVARRIAS'],
            ['JOSE ZENON', 'TORIZ', 'OLVERA'],
            ['SABINO', 'TORIZ', 'OROPEZA'],
            ['RAMOS', 'TRINIDAD', 'PEREZ'],
            ['DARIO', 'VALLES', 'DE LA TRINIDAD'],
            ['TELESFORO', 'VAZQUEZ', 'ESPINOZA'],
            ['ANGEL', 'VAZQUEZ', 'HERNANDEZ'],
            ['CAROLINA', 'VAZQUEZ', 'HERNANDEZ'],
            ['EZEQUIEL', 'VAZQUEZ', 'HERNANDEZ'],
            ['ROCIO', 'VAZQUEZ', 'HERNANDEZ'],
            ['TRINIDAD', 'VAZQUEZ', 'HERNANDEZ'],
            ['MARIA DEL C.', 'VELAZQUEZ', 'HERNANDEZ'],
        ];

        foreach ($datosDart as $index => $fila) {
            $nombreSucio = trim($fila[0]);
            $apPaterno = trim($fila[1]);
            $apMaterno = trim($fila[2] ?? '');

            $nombreLimpio = preg_replace('/\s+/', ' ', $nombreSucio);
            $paternoLimpio = preg_replace('/\s+/', ' ', $apPaterno);
            $maternoLimpio = preg_replace('/\s+/', ' ', $apMaterno);

            $nuevoUsuario = Usuario::updateOrCreate(
                ['Usuario' => 'ejidatario' . (1000 + $index)],
                [
                    'Nombres' => $nombreLimpio,
                    'Apellido_Paterno' => $paternoLimpio,
                    'Apellido_Materno' => $maternoLimpio,
                    'Correo' => 'user' . (1000 + $index) . '@sistema.com',
                    'Contraseña' => Hash::make('secret123'),
                    'Telefono' => '0000000000',
                    'Fecha_Creo' => now(),
                ]
            );

            $payloadParaQR = trim("{$nombreLimpio} {$paternoLimpio} {$maternoLimpio}");

            Ejidatario::updateOrCreate(
                ['Id_Usuario' => $nuevoUsuario->Id_Usuario],
                [
                    'Num_Ejidatario' => 202400 + $index,
                    'qr_payload' => $payloadParaQR,
                    'Id_Estatus' => 1,
                    'Fecha_Ingreso' => now(),

                    // Campos de Dirección
                    'Calle' => 'Conocido',
                    'Num_Exterior' => 'S/N',
                    'Num_Interior' => null,
                    'Colonia' => 'Centro',
                    'Municipio' => 'General',
                    'Estado' => 'Estado',
                    'Codigo_Postal' => '00000',

                    'Fecha_Nacimiento' => '1980-01-01',
                    'CURP' => 'TEMP' . (1000 + $index) . 'XXXXXX00',
                    'RFC' => 'TEMP' . (1000 + $index) . 'XXX',
                    'Clave_Elector' => 'ELECT' . (1000 + $index),
                ]
            );
        }
    }
}