<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Usuario;
use App\Models\Ejidatario;
use Illuminate\Support\Facades\Hash;

class EjidatarioSeeder extends Seeder
{
    public function run()
    {
        $datosDart = [
            ['CARMEN\n', 'AGUILAR', 'AGUIRRE'],
            ['MARIA ISABEL C.\n', 'AGUILAR', 'CAMPOS'],
            ['ASENCION\n', 'AGUILAR', 'CASTILLO'],
            ['LUIS\n', 'AGUILAR', 'ESPINOZA'],
            ['MAXIMINO \n', 'AGUILAR', 'ESPINOZA'],
            ['BENITO\n', 'AGUILAR', 'FLORES'],
            ['CLAUDIO\n', 'AGUILAR', 'HERNANDEZ'],
            ['GILBERTO\n', 'AGUILAR', 'HERNANDEZ'],
            ['DONATO', 'AGUILAR', 'MEZA'],
            ['AGUSTIN', 'AGUILAR', 'MIRANDA'],
            ['CRUZ', 'AGUILAR', 'MIRANDA'],
            ['ODILON', 'AGUILAR', 'MIRANDA'],
            ['RUPERTO', 'AGUIRRE', 'PEREZ'],
            ['GENOVEVA MARCELA', 'AGUIRRE', 'SUAREZ'],
            ['HILARIO\n', 'ARIAS', 'MIRANDA'],
            ['FELIX\n', 'BARRON', 'AGUIRRE'],
            ['VICTOR\n\n', 'BARRON', 'AGUIRRE'],
            ['JOEL\n\n', 'BARRON', 'DAVALOS'],
            ['BONFILIO\n', 'BARRON', 'OLMOS'],
            ['HUMBERTO\n', 'BARRON', 'OLMOS'],
            ['ISMAEL\n\n', 'BARRON', 'OLMOS'],
            ['JAVIER\n\n', 'BARRON', 'OLMOS'],
            ['MARGARITA\n', 'BERNARDINO', 'VAZQUEZ'],
            ['MATILDE\n\n', 'BERNARDINO', 'VAZQUEZ'],
            ['RAFAEL\n', 'BERNARDINO', 'VAZQUEZ'],
            ['MANUELA\n', 'BOBADILLA', 'CABALLERO'],
            ['ALEJANDRA\n', 'BRINDIS', 'ESPINOZA'],
            ['HERMINIO\n', 'BRINDIS', 'HERNANDEZ'],
            ['CRESENCIO \n', 'BRINDIZ', 'AGUIRRE'],
            ['JAVIER\n', 'BRINDIZ', 'AGUIRRE'],
            ['JUANA\n', 'BRINDIZ', 'DE LA LUZ'],
            ['VICTOR\n', 'BRINDIZ', 'ESPINOZA'],
            ['DANIEL\n', 'BRINDIZ', 'FLORES'],
            ['FLORA\n', 'BRINDIZ', 'FLORES'],
            ['PANFILO\n', 'BRINDIZ', 'FLORES'],
            ['FELIMON MARTIN\n', 'BRINDIZ', 'OSORIO'],
            ['FERNANDO\n', 'BRINDIZ', 'OSORIO'],
            ['LEONOR\n', 'CABALLERO', 'BERNARDINO'],
            ['PEDRO\n', 'CABALLERO', 'BERNARDINO'],
            ['RUTH\n', 'CABALLERO', 'CAMPOS'],
            ['BRAULIO\n', 'CABALLERO', 'ESPINOZA'],
            ['CESAR\n', 'CABALLERO', 'ESPINOZA'],
            ['FERNANDO\n', 'CABALLERO', 'ESPINOZA'],
            ['ISMAEL\n', 'CABALLERO', 'ESPINOZA'],
            ['JUAN\n', 'CABALLERO', 'ESPINOZA'],
            ['MARICELA\n', 'CABALLERO', 'ESPINOZA'],
            ['REYNALDO\n', 'CABALLERO', 'ESPINOZA'],
            ['VICTOR\n', 'CABALLERO', 'ESPINOZA'],
            ['JOSE BENJAMIN\n', 'CABALLERO', 'HERNANDEZ'],
            ['RICARDO\n\n', 'CABALLERO', 'HERNANDEZ'],
            ['SALOMON TOMAS\n', 'CABALLERO', 'HERNANDEZ'],
            ['SARA\n', 'CABALLERO', 'HERNANDEZ'],
            ['JOSE\n', 'CABALLERO', 'MELCHOR'],
            ['BONFILIO\n', 'CABALLERO', 'MIRANDA'],
            ['FERMINA\n', 'CABALLERO', 'MIRANDA'],
            ['GABRIEL\n', 'CABALLERO', 'MIRANDA'],
            ['CONCEPCION\n', 'CABALLERO', 'OSORIO'],
            ['JUAN\n', 'CABALLERO', 'OSORIO'],
            ['SEBASTIAN\n', 'CABALLERO', 'OSORIO'],
            ['FILEMON\n', 'CABALLERO', 'PASTRAN'],
            ['GABRIEL\n', 'CABALLERO', 'PASTRAN'],
            ['NICANOR\n', 'CABALLERO', 'PASTRAN'],
            ['ALEJANDRA JULIA\n', 'CABALLERO', 'PEREZ'],
            ['CARMEN\n', 'CABALLERO', 'PEREZ'],
            ['INOCENCIO\n', 'CABALLERO', 'PEREZ'],
            ['JORGE PEDRO\n', 'CABALLERO', 'PEREZ'],
            ['MELITON\n', 'CABALLERO', 'PEREZ'],
            ['NICOLAS\n', 'CABALLERO', 'PEREZ'],
            ['SALVADOR\n', 'CABALLERO', 'PEREZ'],
            ['SERGIO 1 HERM JULIA\n', 'CABALLERO', 'PEREZ'],
            ['SERGIO 2\n', 'CABALLERO', 'PEREZ'],
            ['JUAN\n\n', 'CABALLERO', 'RIOS'],
            ['ANA MARIA\n', 'CABALLERO', 'ROSAS'],
            ['FIDEL\n', 'CABALLERO', 'ROSAS'],
            ['TEODORO\n', 'CABALLERO', 'ROSAS'],
            ['ANGELA ZENAIDA\n', 'CABALLERO', 'SANCHEZ'],
            ['CECILIO DEMETRIO\n', 'CABALLERO', 'SANCHEZ'],
            ['TRINIDAD\n', 'CABALLERO', 'VAZQUEZ'],
            ['OLGA\n', 'CABRERA', 'CARRILLO'],
            ['SANTIAGO\n', 'CABRERA', 'ESPINOZA'],
            ['JOSE LUIS\n', 'CABRERA', 'HERNANDEZ'],
            ['CONCEPCION\n', 'CAMPOS', 'FLORES'],
            ['MARIA\n', 'CHAVARRIAS', 'AGUILAR'],
            ['ROBERTO\n', 'CONTRERAS', 'OLMOS'],
            ['CRESENCIO\n', 'DAVALOS', 'AREVALO'],
            ['ISIDRO\n', 'DAVALOS', 'AREVALO'],
            ['ALFREDO\n', 'DAVALOS', 'CORDOVA'],
            ['DOMITILO\n', 'DAVALOS', 'CORDOVA'],
            ['PASCUAL\n', 'DAVALOS', 'CORDOVA'],
            ['FRANCISCO\n', 'DAVALOS', 'DEL PILAR'],
            ['MANUEL\n', 'DAVALOS', 'DEL PILAR'],
            ['MISAEL\n', 'DAVALOS', 'DEL PILAR'],
            ['CASTO\n', 'DAVALOS', 'ESPINOZA'],
            ['FILEMON\n', 'DAVALOS', 'ESPINOZA'],
            ['JOSE JORGE\n', 'DAVALOS', 'ESPINOZA'],
            ['SERGIO\n', 'DAVALOS', 'ESPINOZA'],
            ['TOMAS\n', 'DAVALOS', 'ESPINOZA'],
            ['AMADO\n', 'DAVALOS', 'HERNANDEZ'],
            ['J. PEDRO ABEL\n', 'DAVALOS', 'HERNANDEZ'],
            ['JAIME\n', 'DAVALOS', 'MIRANDA'],
            ['JOSE\n', 'DAVALOS', 'MIRANDA'],
            ['PEDRO\n', 'DAVALOS', 'MIRANDA'],
            ['MANUEL\n', 'DAVALOS', 'PEREZ'],
            ['INOCENCIO\n', 'DE LA LUZ', 'CABALLERO'],
            ['JUAN\n', 'DE LA LUZ', 'CABALLERO'],
            ['MARIA ZARAPIA\n', 'OROPEZA', 'DE LA LUZ'],
            ['CARMEN\n', 'DE LA LUZ', 'TORIZ'],
            ['BALVINA\n', 'DE LA TRINIDAD', 'OSORIO'],
            ['ADELFO\n\n', 'DIAZ', 'AGUILAR'],
            ['AMADOR\n\n', 'DIAZ', 'AGUILAR'],
            ['JUAN\n', 'DIAZ', 'AGUILAR'],
            ['PERFECTO\n', 'DIAZ', 'AGUILAR'],
            ['ROSENDO\n', 'DIAZ', 'AGUILAR'],
            ['BRUNO\n', 'DIAZ', 'FLORES'],
            ['DEMETRIO\n', 'DIAZ', 'FLORES'],
            ['MARTHA\n', 'DIAZ', 'ROSAS'],
            ['MANUELA\n\n', 'DIAZ', 'MEZA'],
            ['AGUSTIN\n\n\n', 'DIAZ', 'ROSAS'],
            ['ANGEL \n\n', 'DIAZ', 'ROSAS'],
            ['GUILLERMO\n', 'DIAZ', 'ROSAS'],
            ['DOMINGO ARENAS\n', 'ESCUELA', 'PRIMARIA'],
            ['MARIA SANTIAGA\n', 'ESPINOZA', 'AGUILAR'],
            ['ROSENDO\n', 'ESPINOZA', 'AGUIRRE'],
            ['RAYMUNDO\n', 'ESPINOZA', 'ARMENTA'],
            ['FERNANDO\n', 'ESPINOZA', 'CABALLERO'],
            ['GERARDO\n', 'ESPINOZA', 'CABALLERO'],
            ['ARISTEO ANTONIO\n', 'ESPINOZA', 'CHAVARRIAS'],
            ['FRANCISCO\n', 'ESPINOZA', 'CHAVARRIAS'],
            ['EFREN\n', 'ESPINOZA', 'DAVALOS'],
            ['GABRIEL\n', 'ESPINOZA', 'FLORES'],
            ['SEVERO\n', 'ESPINOZA', 'FLORES'],
            ['TRINIDAD\n', 'ESPINOZA', 'HERNANDEZ'],
            ['SABINO\n', 'ESPINOZA', 'JUAREZ'],
            ['MARIA PAULA PETRA\n', 'ESPINOZA', 'JURADO'],
            ['MARGARITO\n', 'ESPINOZA', 'LOPEZ'],
            ['ELIGIO\n', 'ESPINOZA', 'MARIN'],
            ['FRANCISCO\n', 'ESPINOZA', 'MORALES'],
            ['GAVINO\n', 'ESPINOZA', 'MORALES'],
            ['JESUS\n', 'ESPINOZA', 'MORALES'],
            ['MICAELA\n', 'ESPINOZA', 'MORALES'],
            ['HONORIA\n', 'ESPINOZA', 'MUÑOZ'],
            ['GUILLERMO\n', 'ESPINOZA', 'OROPEZA'],
            ['PASCUAL\n', 'ESPINOZA', 'OROPEZA'],
            ['ARGIMINA\n', 'ESPINOZA', 'OSORIO'],
            ['BENJAMIN\n', 'ESPINOZA', 'OSORIO'],
            ['ISMAEL\n', 'ESPINOZA', 'OSORIO'],
            ['MARGARITA\n', 'ESPINOZA', 'OSORIO'],
            ['PASCUALA\n', 'ESPINOZA', 'OSORIO'],
            ['PABLO', 'ESPINOZA', ''],
            ['TRINIDAD\n', 'ESPINOZA', 'PALMA'],
            ['ANASTACIO\n', 'ESPINOZA', 'PEREZ'],
            ['CIRILO\n', 'ESPINOZA', 'PEREZ'],
            ['HILARIO\n', 'ESPINOZA', 'PEREZ'],
            ['JOSE INDALECIO\n', 'ESPINOZA', 'PEREZ'],
            ['RAMON\n', 'ESPINOZA', 'PEREZ'],
            ['ROBERTO\n', 'ESPINOZA', 'PEREZ'],
            ['TEOFILO\n', 'ESPINOZA', 'PEREZ'],
            ['ERASMO\n', 'ESPINOZA', 'RAMIREZ'],
            ['JUAN\n', 'ESPINOZA', 'RAMIREZ'],
            ['MACLOVIA\n', 'ESPINOZA', 'RAMIREZ'],
            ['MAXIMINO\n', 'ESPINOZA', 'RAMIREZ'],
            ['RAFAEL\n', 'ESPINOZA', 'RAMIREZ'],
            ['JUVENCIA\n\n', 'ESPINOZA', 'SANDOVAL'],
            ['GUSTAVO\n', 'ESPINOZA', 'IGLESIAS'],
            ['MARIA GUADALUPE\n', 'ESPINOZA', 'SANCHEZ'],
            ['JUANA\n', 'ESPINOSA', 'VALLEJO'],
            ['RICARDO\n', 'ESPINOZA', 'VALLEJO'],
            ['ROBERTO\n', 'ESPINOZA', 'VALLEJO'],
            ['FILIBERTA\n', 'ESPINOZA', 'VARGAS'],
            ['FLORENCIO\n', 'ESPINOZA', 'VARGAS'],
            ['GERARDO\n', 'ESPINOZA', 'VARGAS'],
            ['GIL\n\n', 'ESPINOZA', 'VARGAS'],
            ['MARGARITA\n', 'ESPINOZA', 'VARGAS'],
            ['PASCUALA\n', 'ESPINOZA', 'VARGAS'],
            ['TEODORO\n', 'ESPINOZA', 'VARGAS'],
            ['GABRIEL\n', 'ESPINOZA', 'VAZQUEZ'],
            ['EVA\n', 'FLORES', 'HUESCA'],
            ['NAZARIO\n', 'FLORES', 'LOPEZ'],
            ['IGNACIO\n', 'FLORES', 'MARIN'],
            ['ANSELMO\n', 'FLORES', 'SANCHEZ'],
            ['PASCUAL\n', 'HERMENEGILDO', 'CHAVARRIAS'],
            ['HERIBERTO\n', 'HERNANDEZ', 'DEL PILAR'],
            ['PEDRO\n', 'HERNANDEZ', 'DEL PILAR'],
            ['MARGARITO\n', 'HERNANDEZ', 'DIAZ'],
            ['SALVADOR\n', 'HERNANDEZ', 'DIAZ'],
            ['RAFAELA\n', 'HERNANDEZ', 'ESPINOZA'],
            ['FILOMENA\n', 'HERNANDEZ', 'OSORIO'],
            ['PASCUAL\n', 'HERNANDEZ', 'OSORIO'],
            ['CANDIDO\n', 'HERNANDEZ', 'PEREZ'],
            ['JOSE CRUZ\n', 'HERNANDEZ', 'PEREZ'],
            ['JUSTO\n', 'HERNANDEZ', 'PEREZ'],
            ['ROBERTA\n', 'HERNANDEZ', 'ROJAS'],
            ['TOMAS\n', 'HERNANDEZ', 'FLORES'],
            ['JOAQUINA\n', 'HERNANDEZ', 'SANDOVAL'],
            ['DANIEL\n', 'HERNANDEZ', 'TRINIDAD'],
            ['FIDENCIO\n', 'IGLESIAS', 'AGUIRRE'],
            ['MARTINA\n', 'IGLESIAS', 'AGUIRRE'],
            ['MEDARDO\n', 'IGLESIAS', 'AGUIRRE'],
            ['CATALINA\n', 'IGLESIAS', 'CABALLERO'],
            ['MARCELINO\n', 'IGLESIAS', 'CABALLERO'],
            ['PETRA\n\n', 'JIMENEZ', 'LOPEZ'],
            ['MAXIMO\n', 'JUAREZ', 'AGUILAR'],
            ['MARIA REMEDIOS\n', 'JUAREZ', 'AGUIRRE'],
            ['ANASTACIO\n', 'JUAREZ', 'CESAREO'],
            ['ELIA\n', 'JUAREZ', 'DE LA LUZ'],
            ['SAUL\n', 'JUAREZ', 'DE LA LUZ'],
            ['ALEJANDRINO\n', 'JUAREZ', 'ESPINOZA'],
            ['CAMILO\n', 'JUAREZ', 'ESPINOZA'],
            ['FAUSTINO\n', 'JUAREZ', 'ESPINOZA'],
            ['FRANCISCO\n', 'JUAREZ', 'ESPINOZA'],
            ['JOSE PERFECTO\n', 'JUAREZ', 'ESPINOZA'],
            ['JUAN\n', 'JUAREZ', 'ESPINOZA'],
            ['ADALBERTO\n', 'JUAREZ', 'HERNANDEZ'],
            ['FRANCISCA\n', 'LIRA', 'SEGUNDO'],
            ['RUFINA\n\n', 'LIRA', 'SEGUNDO'],
            ['LUIS\n', 'LOZANO', 'DE LA TRINIDAD'],
            ['MARCOS\n', 'LOZANO', 'OLVERA'],
            ['FELIPE\n', 'LOZANO', 'OSORIO'],
            ['GENARO\n', 'LOZANO', 'OSORIO'],
            ['IRINEO\n', 'LOZANO', 'OSORIO'],
            ['ANGELICA\n', 'MARTINEZ', 'MIGUEL'],
            ['JOSE PEDRO JUVENAL \n', 'MARTINEZ', 'OROPEZA'],
            ['MARIA\n', 'MIRANDA', 'JUAREZ'],
            ['ANASTACIO\n', 'MORALES', 'OLMOS'],
            ['LORENZO\n', 'MORALES', 'OLMOS'],
            ['MARCELINO\n', 'MORALES', 'OLMOS'],
            ['FRANCISCO\n', 'MORENO', 'JUAREZ'],
            ['JOSE ASENCION\n', 'MUÑOZ', 'CESAREO'],
            ['JOSE TEODORO\n', 'MUÑOZ', 'CESAREO'],
            ['MARCELO\n', 'OJEDA', 'DAVALOS'],
            ['OBDULIO\n', 'OJEDA', 'DAVALOS'],
            ['ELIAS\n', 'OJEDA', 'ESPINOZA'],
            ['JOSE JUVENTINO\n', 'OJEDA', 'RODRIGUEZ'],
            ['MANUEL\n', 'OJEDA', 'RODRIGUEZ'],
            ['PLUTARCO\n', 'OJEDA', 'RODRIGUEZ'],
            ['ODILON\n', 'OJEDA', 'VAZQUEZ'],
            ['GREGORIO\n', 'OLMOS', 'ESPINOZA'],
            ['ASUNCION\n', 'OLMOS', 'HERNANDEZ'],
            ['CIRILO\n', 'OLMOS', 'HERNANDEZ'],
            ['MARCELO\n', 'OLMOS', 'HERNANDEZ'],
            ['ENRIQUE\n', 'OLMOS', 'SEGUNDO'],
            ['AURORA\n', 'OLVERA', 'MOCTEZUMA'],
            ['LUCIO\n', 'OROPEZA', 'ESPINOZA'],
            ['LUCAS\n', 'OROPEZA', 'ESPINOZA'],
            ['ANASTACIO\n', 'OROPEZA', 'OSORIO'],
            ['CARMEN\n', 'OROPEZA', 'OSORIO'],
            ['GERARDO\n', 'OROPEZA', 'OSORIO'],
            ['JUAN ASCENCION\n', 'OROPEZA', 'OSORIO'],
            ['MARGARITO\n', 'OROPEZA', 'OSORIO'],
            ['PASCUALA \n', 'OROPEZA', 'OSORIO'],
            ['MARCIANO\n', 'OROPEZA', 'RAMIREZ'],
            ['ELIZA\n', 'OROPEZA', 'SANCHEZ'],
            ['DAVID\n', 'OROPEZA', 'SUAREZ'],
            ['DELFINO\n', 'OROPEZA', 'SUAREZ'],
            ['ESTEBAN\n', 'OROPEZA', 'SUAREZ'],
            ['PETRA\n', 'OROPEZA', 'SUAREZ'],
            ['FLORENCIO\n', 'ORTIZ', 'JIMENEZ'],
            ['GABINO\n', 'OSORIO', 'AGUILAR'],
            ['ROSALINO\n', 'OSORIO', 'AGUILAR'],
            ['EVERARDO\n', 'OSORIO', 'AGUIRRE'],
            ['MARTINA\n', 'OSORIO', 'AGUIRRE'],
            ['FLORENCIO\n', 'OSORIO', 'ALMAZAN'],
            ['JOSE VICTOR DAVID\n', 'OSORIO', 'BERNARDINO'],
            ['LEOPOLDO\n', 'OSORIO', 'BERNARDINO'],
            ['JAIME\n', 'OSORIO', 'CABALLERO'],
            ['HILARIA\n', 'OSORIO', 'CABRERA'],
            ['GUILLERMO\n', 'OSORIO', 'CAMPOS'],
            ['FELIPE\n', 'OSORIO', 'CASTILLO'],
            ['CAMILO\n', 'OSORIO', 'DAVALOS'],
            ['CELSO\n', 'OSORIO', 'DAVALOS'],
            ['FELIPE\n', 'OSORIO', 'DAVALOS'],
            ['FRANCISCO\n', 'OSORIO', 'ESPINOZA'],
            ['MISRRAIM\n', 'OSORIO', 'ESPINOZA'],
            ['ALFREDO\n', 'OSORIO', 'HERNANDEZ'],
            ['APOLINAR JAIME\n', 'OSORIO', 'HERNANDEZ'],
            ['GREGORIO\n', 'OSORIO', 'HERNANDEZ'],
            ['JAVIER\n', 'OSORIO', 'HERNANDEZ'],
            ['FELIPE\n', 'OSORIO', 'JUAREZ'],
            ['APOLINAR\n', 'OSORIO', 'LOZANO'],
            ['FRANCISCO\n', 'OSORIO', 'MEZA'],
            ['ROBERTO\n', 'OSORIO', 'MONTAÑO'],
            ['EULALIO\n', 'OSORIO', 'MORENO'],
            ['TEODORO\n', 'OSORIO', 'OJEDA'],
            ['MARIA MERCEDES\n', 'OSORIO', 'OROPEZA'],
            ['ARTURO\n', 'OSORIO', 'OSORIO'],
            ['HIGINIO\n\n', 'OSORIO', 'OSORIO'],
            ['PEDRO\n', 'OSORIO', 'OSORIO'],
            ['BENITO\n', 'OSORIO', 'PARRA'],
            ['DANIEL\n\n', 'OSORIO', 'PARRA'],
            ['FAUSTINO\n', 'OSORIO', 'PARRA'],
            ['FRANCISCO\n', 'OSORIO', 'PARRA'],
            ['ODILON\n', 'OSORIO', 'PARRA'],
            ['INES\n', 'OSORIO', 'PEREZ'],
            ['JOSEFA\n\n', 'OSORIO', 'PEREZ'],
            ['VICENTE\n', 'OSORIO', 'PEREZ'],
            ['JOSE NOE PANFILO\n', 'OSORIO', 'RIOS'],
            ['ALBERTO \n', 'OSORIO', 'SANCHEZ'],
            ['JUAN RODOLFO\n', 'OSORIO', 'SANCHEZ'],
            ['JUVENTINO\n', 'OSORIO', 'SANCHEZ'],
            ['ANASTACIA\n', 'OSORIO', 'TORIZ'],
            ['ELIAS\n', 'OSORIO', 'VAZQUEZ'],
            ['LAZARO\n', 'PADILLA', 'HERNANDEZ'],
            ['FELICITAS\n', 'PADILLA', 'PEREZ'],
            ['JESUS\n', 'PADILLA', 'PEREZ'],
            ['JUAN\n', 'PADILLA', 'PEREZ'],
            ['AMBROCIA GUADALUPE\n', 'PADRON', 'SANCHEZ'],
            ['ARCANGEL \n', 'PARROQUIA SAN', 'RAFAEL'],
            ['CLEOTILDE\n', 'PEREZ', 'AGUIRRE'],
            ['ISABEL\n\n', 'PEREZ', 'DAVALOS'],
            ['CANDELARIO\n\n', 'PEREZ', 'DIAZ'],
            ['ALFONSO\n', 'PEREZ', 'ESPINOZA'],
            ['FELIPE\n', 'PEREZ', 'ESPINOZA'],
            ['JOSE \n', 'PEREZ', 'ESPINOZA'],
            ['JOSE LUIS\n', 'PEREZ', 'ESPINOZA'],
            ['JOSE MARIA\n', 'PEREZ', 'ESPINOZA'],
            ['MANUEL\n', 'PEREZ', 'ESPINOZA'],
            ['PABLO\n', 'PEREZ', 'ESPINOZA'],
            ['PEDRO\n', 'PEREZ', 'ESPINOZA'],
            ['ZEFERINO\n', 'PEREZ', 'ESPINOZA'],
            ['ANDRES\n', 'PEREZ', 'HERNANDEZ'],
            ['ODILON\n', 'PEREZ', 'HERNANDEZ'],
            ['RITO\n', 'PEREZ', 'HERNANDEZ'],
            ['ROBERTA\n', 'PEREZ', 'HERNANDEZ'],
            ['MARIA DE LA LUZ\n', 'PEREZ', 'MAGAÑA'],
            ['JOSE ROBERTO\n', 'PEREZ', 'MORALES'],
            ['GAVINO\n', 'PEREZ', 'MORENO'],
            ['JUAN\n', 'PEREZ', 'MORENO'],
            ['JULIA\n', 'PEREZ', 'NEGRETE'],
            ['RAFAELA\n', 'PEREZ', 'OSORIO'],
            ['ANGEL\n', 'PEREZ', 'PEREZ'],
            ['FORTINO\n', 'PEREZ', 'SEGUNDO'],
            ['TEODORO ALFONSO\n', 'PEREZ', 'VAZQUEZ'],
            ['MARINA\n', 'RAMIREZ', 'OSORIO'],
            ['JOAQUINA\n', 'RIOS', 'AGUILAR'],
            ['MARTIN\n', 'RIOS', 'AGUILAR'],
            ['NICOLAS\n', 'RIOS', 'AGUILAR'],
            ['ADRIAN\n', 'RIOS', 'CHAVARRIAS'],
            ['EUSEBIO\n', 'RIOS', 'CHAVARRIAS'],
            ['CARMEN\n', 'RIOS', 'ESPINOZA'],
            ['MICAELA\n', 'RIOS', 'ESPINOZA'],
            ['AMBROCIO\n', 'RIOS', 'IGLESIAS'],
            ['ELENA\n', 'RIOS', 'IGLESIAS'],
            ['HIPOLITO\n', 'RIOS', 'IGLESIAS'],
            ['JOAQUIN\n', 'RIOS', 'IGLESIAS'],
            ['ARCADIO\n', 'RIOS', 'PEREZ'],
            ['FAUSTO\n', 'RIOS', 'PEREZ'],
            ['HERON\n', 'RIOS', 'PEREZ'],
            ['MAGDALENO\n', 'RIOS', 'PEREZ'],
            ['RAFAEL\n', 'RIOS', 'PEREZ'],
            ['MARCIAL\n', 'RIOS', 'SANCHEZ'],
            ['JOSE MAURO\n', 'RODRIGUEZ', 'OJEDA'],
            ['JUAN\n', 'RODRIGUEZ', 'OJEDA'],
            ['RITO\n', 'RODRIGUEZ', 'OJEDA'],
            ['AGUSTIN\n', 'RODRIGUEZ', 'SANCHEZ'],
            ['FLORENTINO\n', 'ROSAS', 'AGUIRRE'],
            ['ANTONIO\n', 'ROSAS', 'PEREZ'],
            ['BENJAMIN\n', 'SANCHEZ', 'AGUIRRE'],
            ['CLAUDIO\n', 'SANCHEZ', 'AGUIRRE'],
            ['JOSE\n', 'SANCHEZ', 'AGUIRRE'],
            ['CRISTOBAL\n', 'SANCHEZ', 'ESPINOZA'],
            ['DELFINO\n', 'SANCHEZ', 'ESPINOZA'],
            ['GERMAN\n', 'SANCHEZ', 'ESPINOZA'],
            ['MANUEL \n', 'SANCHEZ', 'FLORES'],
            ['MIGUEL\n', 'SANCHEZ', 'HERNANDEZ'],
            ['PEDRO\n', 'SANCHEZ', 'HERNANDEZ'],
            ['AGUSTIN\n', 'SANCHEZ', 'OROPEZA'],
            ['ENRIQUE\n', 'SANCHEZ', 'OSORIO'],
            ['CARLOS\n', 'SANCHEZ', 'PARRA'],
            ['HILARIO\n', 'SEGUNDO', 'ESPINOZA'],
            ['J. ASCENCION\n', 'SEGUNDO', 'JUAREZ'],
            ['JOSE ANTONIO\n', 'SEGUNDO', 'MONTAÑO'],
            ['FRANCISCO\n', 'SEGUNDO', 'PEREZ'],
            ['GREGORIO\n', 'SEGUNDO', 'PEREZ'],
            ['LUIS\n', 'SEGUNDO', 'PEREZ'],
            ['MARTINA\n', 'SEGUNDO', 'PEREZ'],
            ['ROGACIANO\n', 'SEGUNDO', 'PEREZ'],
            ['GRACIANO\n', 'SILVA', 'AGUIRRE'],
            ['JUAN\n', 'SILVA', 'DAVALOS'],
            ['RAFAEL\n', 'SILVA', 'DAVALOS'],
            ['JUAN MARTIN\n', 'SILVA', 'VALLES'],
            ['OCTAVIO\n', 'SILVA', 'VALLES'],
            ['PEDRO\n', 'SUAREZ', 'CORTES'],
            ['ARCADIO\n', 'SUAREZ', 'OSORIO'],
            ['EUSEBIO\n', 'SUAREZ', 'OSORIO'],
            ['FELIX 1 \n', 'SUAREZ', 'OSORIO'],
            ['FELIX 2 (CALANZINGO)\n', 'SUAREZ', 'OSORIO'],
            ['FRANCISCO\n\n', 'SUAREZ', 'OSORIO'],
            ['NARCIZO\n', 'SUAREZ', 'OSORIO'],
            ['PEDRO\n', 'SUAREZ', 'OSORIO'],
            ['RUFINO\n', 'SUAREZ', 'OSORIO'],
            ['SAMUEL \n', 'SUAREZ', 'OSORIO'],
            ['WVILLADO\n', 'TORIZ', 'CHAVARRIAS'],
            ['JOSE ZENON\n', 'TORIZ', 'OLVERA'],
            ['SABINO\n', 'TORIZ', 'OROPEZA'],
            ['RAMOS\n', 'TRINIDAD', 'PEREZ'],
            ['DARIO\n', 'VALLES', 'DE LA TRINIDAD'],
            ['TELESFORO\n', 'VAZQUEZ', 'ESPINOZA'],
            ['ANGEL\n', 'VAZQUEZ', 'HERNANDEZ'],
            ['CAROLINA\n', 'VAZQUEZ', 'HERNANDEZ'],
            ['EZEQUIEL\n', 'VAZQUEZ', 'HERNANDEZ'],
            ['ROCIO\n', 'VAZQUEZ', 'HERNANDEZ'],
            ['TRINIDAD\n', 'VAZQUEZ', 'HERNANDEZ'],
            ['MARIA DEL C.\n', 'VELAZQUEZ', 'HERNANDEZ'],
        ];

        foreach ($datosDart as $index => $fila) {
            $nombreSucio = $fila[0];
            $apPaterno = $fila[1];
            $apMaterno = $fila[2] ?? '';

            $nombreLimpio = trim(str_replace(["\n", "\r"], ' ', $nombreSucio));

            // 2. Creamos el Usuario primero
            $nuevoUsuario = Usuario::create([
                'Nombres'          => $nombreLimpio,
                'Apellido_Paterno' => $apPaterno,
                'Apellido_Materno' => $apMaterno,
                'Usuario'          => 'ejidatario' . (1000 + $index),
                'Correo'           => 'user' . (1000 + $index) . '@sistema.com',
                'Contraseña'       => Hash::make('secret123'),
                'Telefono'         => '0000000000',
                'Fecha_Creo'       => now(),
            ]);

            $payloadParaQR = "{$nombreSucio} {$apPaterno} {$apMaterno}";

            Ejidatario::create([
                'Id_Usuario'     => $nuevoUsuario->Id_Usuario,
                'Num_Ejidatario' => 202400 + $index,
                'qr_payload'     => $payloadParaQR,
                'Id_Estatus'     => 1,
                'Fecha_Ingreso'  => now(),
            ]);
        }
    }
}