[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "mysql80", "pkg-config", "libmysqlclient"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm install && npm run build"]

[variables]
PHP_EXTENSION_INSTALLER = "pdo_mysql,mysqli,mbstring,gd,xml,zip"
NIXPACKS_PHP_FALLBACK_BINARY = "php82"