[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "mysql80", "pkg-config", "libmysqlclient"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "docker-php-ext-install pdo_mysql"
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm install && npm run build"]

[variables]
PHP_EXTENSION_INSTALLER = "pdo_mysql"
NIXPACKS_PHP_FALLBACK_BINARY = "php83"