[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "mysql80"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install && npm run build"
]

[variables]
PHP_EXTENSION_INSTALLER = "pdo_mysql,mysqli,gd,mbstring,xml,zip"